name: Deploy to Vercel

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'  

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: npx vercel --prod --token $VERCEL_TOKEN